### PR TITLE
[10.0][ADD] medical_practitioner_us: New module with US practitioner IDs

### PR DESCRIPTION
**Pull request by obulkin**
[ADD] ``medical_practitioner_us``: New module with US IDs
* Create standard module components (manifest, README, etc.)
* Add ``res.partner.id_category`` record corresponding to US state license numbers
* Add several ID fields relevant to US medical practitioners to ``res.partner`` and surface them in medical practitioner views
* Add relevant unit tests

This PR depends on:

- [x] https://github.com/OCA/vertical-medical/pull/196

### CODE REVIEW

**Comment by lasley** [comment]
@obulkin - please rebase now that depend is merged

**Comment by obulkin** [comment]
@lasley - The branch has been rebased and should be ready for review.

**Review by lasley — APPROVED** [review]
Thanks @obulkin

**Comment by lasley** [comment]
No other reviewers for this version. I am moving forward with merge

**Pull request merged**
