### PR TITLE
[8.0-incubator] Move medical_emr to __unported__

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
This PR move the module `medical_emr` (and medical_operational that depends on it), with #39 improvements, into `__unported__` in order to restart/continue work from a sane basis.
This basis is defined by the way to `port` modules into the `8.0-incubator` branch: https://github.com/OCA/vertical-medical/wiki/8.0-Incubator-Objectives

Doing this will allow us to start the split of ERM doing pull requests per functional features. (as wiki explainations)

So After the merge of this pull request we can continue the work done into #39 

Jonathan

### CODE REVIEW

**Comment by lmignon** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by sbidoul** [comment]
Note in the (near) future the `__unported__` will disappear and uninstallable modules will move to the root of the repo. This is for 9.0 but may be applied to the 8.0 branch too.

If the addon medical_emr is going to be progressively emptied, this PR is ok. Otherwise if medical_emr is the name of a ported module, you should rename it to something else so they don't conflict in the repo root.

**Comment by JonathanNEMRY** [comment]
Hi @sbidoul 
I think the module is going to be emptied as it's name is a general concept: if we start to split/move features into smallers one then I do not think `medical_emr` will still be necessary.

Jonathan

**Comment by Olivier-LAURENT** [comment]
Hi @lasley,
Do you agree with this PR ?

**Comment by Olivier-LAURENT** [comment]
:+1:

**Comment by lasley** [comment]
I do! :+1:

**Comment by JonathanNEMRY** [comment]
Great! thanks all!
#44 is now rebased on `oca/8.0-incubator` and ready to be reviewed

**Pull request merged**
