### PR TITLE
[9.0][MIG] medical medication us

### PR DESCRIPTION
**Pull request by lasley**
This is dependent on #75

### CODE REVIEW

**Comment by lasley** [comment]
Rebased and updated to incubator code. This is ready for review.

cc @tedsalmon @kellylougheed

**Comment by lasley** [comment]
Note this is being merged into medical_medicament for v10. History behind this was that we had already launched v9 on customers internally & thus the models were locked down. We just beat the model lock on v10 with this, so we're good to put it in medical.

**Comment by kellylougheed** [comment]
It looks like this module is just being deleted -- is that what's going on?

**Comment by lasley** [comment]
Yup, seems that was deprecated for #149. We should actually include in there - I'll cherry pick it over. Thanks for the catch @kellylougheed

**Pull request closed without merging**
