### PR TITLE
Release/9.0

### PR DESCRIPTION
**Pull request by lasley**
Hi all!

Apologies - we were advised not to work on this branch before 8.0 was approved, but we're working with some pretty hard deadlines that couldn't be held up.

We have rebased this branch on top of suggestions provided in #66 (aside from the commit squash, which I cannot complete without wrecking the repo).

This PR includes the following modules. Test coverage has increased to a hair under 90% (https://coveralls.io/builds/4913483):
-  medical
- medical_base_history
- medical_appointment
- medical_pathology
- medical_patient_disease
- medical_patient_disease_allergy
- medical_medicament
- medical_medication
- medication_medication_us
- medical_pharmacy
- medical_pharmacy_us
- medical_prescription

@pedrobaeza - I apologize for the haphazard commits earlier that I can't figure out how to clean up. Hopefully these are better.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is there any possibility to extract each module in one PR? You can follow this guide and the add missing commits to make it compatible with v9: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0.

Anyway, you need to rebase this on top of 9.0 branch.

**Comment by lasley** [comment]
Yes, I can most definitely do that. Just to make sure I understand, I should close this PR and submit one per module - each including requirements of the linked migration doc?

**Comment by lasley** [comment]
Also, possible to switch 9.0 to the current 8.0 + the script to upgrade? Will make things much easier :smile:

**Comment by pedrobaeza** [comment]
Let me think again: we agreed to rebuild again the 9.0 branch when 8.0 is merged, so you don't need to include the commits again. So these are the tasks:
- I'm going to recreate 9.0 branch from 8.0 one.
- This migration puts all modules as uninstallable.
- You have to get this new 9.0 branch in a separate folder, keeping current 9.0.
- Copy or cherry-pick the commits specific for the 9.0 migration.
- Make PR for this module.

I'll ping you in this PR when done.

**Comment by lasley** [comment]
Got it, thanks @pedrobaeza - easy enough to cherry pick the modules into their own PRs.

**Comment by pedrobaeza** [comment]
OK, @lasley, 9.0 branch is now recreated. You can go on.

**Comment by lasley** [comment]
Awesome, thanks @pedrobaeza - I'll nail these out in the morning

**Pull request closed without merging**
