### PR TITLE
[10.0][ADD] medical_agpl: Module for AGPL assets

### PR DESCRIPTION
**Pull request by lasley**
* Add AGPL modules that improve vertical medical

This module is not necessary for the operation of most of Vertical Medical, but does add some nifty logic that is worth having.

cc @LasLabs @Eficent

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by lasley** [comment]
@obulkin please review

**Comment by obulkin** [comment]
@lasley - Everything looks fine here, but the module is basically just a skeleton. Is there something missing from the PR, or is the purpose just to install AGPL dependencies?

**Comment by woodbrettm** [comment]
Also need partner_contact_weight I believe in the depends

**Comment by lasley** [comment]
@obulkin - the purpose is basically just to bind in AGPL dependencies and provide a clear path for AGPL code to travel in our ecosystem. If anything depends on this, it is an AGPL module. A similar concept can be seen in [l10n_us_account_profile](https://github.com/OCA/l10n-usa/tree/10.0/l10n_us_account_profile).

@bmw95 `partner_contact_weight` added

**Comment by obulkin** [comment]
@lasley - Got it. In that case, everything looks good to me.

**Review by obulkin — APPROVED** [review]

**Pull request merged**
