### PR TITLE
[8.0 incubator] FIX medical his

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
- Fix inherit bad naming
- add missing context for institution
- add missing inverse relation and smart buttons for
  - zone->zone
  - zone->room
  - room->bed

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by lasley** [comment]
:+1:

**Comment by JonathanNEMRY** [comment]
Thanks all!

**Pull request merged**
