### PR TITLE
7.0 fix pep8

### PR DESCRIPTION
**Pull request by yvaucher**
Superseeds #2

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There are still a few pep8 issues

**Comment by yvaucher** [comment]
@pedrobaeza No more lint and pep8 errors

**Comment by pedrobaeza** [comment]
Great!

:+1:

**Comment by rvalyi** [comment]
cleanup looks good.
However it seems there is a real issue with loading some missing XML resource, see Travis report:
https://travis-ci.org/OCA/vertical-medical/jobs/48238692#L352
This error doesn't seem to be caused by the cleanup, this is really because for some reason this menu references a action window that is not defined by the module:
https://github.com/OCA/vertical-medical/blob/7.0/oemedical_gynecology_and_obstetrics/views/oemedical_menu.xml#L13

**Comment by yvaucher** [comment]
@rvalyi error has already been reported here: https://github.com/OCA/vertical-medical/issues/4

It will need some work to redefine completely the menu in oemedical_gynecolagy_and_obstetrics unless we set it as uninstallable.

**Comment by pedrobaeza** [comment]
I merge, waiting for a check on the server part.

**Pull request merged**
