### PR TITLE
8.0 incubator

### PR DESCRIPTION
**Pull request by gagzvirk**

### CODE REVIEW

**Comment by nhomar** [comment]
@gagzvirk 

Do I asume it is the last version ready for merge?

I see the last commit was the one approved by @pedrobaeza 

Can I merge it?

**Comment by lmignon** [comment]
@nhomar @gagzvirk IMO the incubator branch is not ready to merge into 8.0. Lots of thinks remains to be cleaned and refactored that's why the incubator branch exists.

**Comment by nhomar** [comment]
@lmignon 

Ok Excellent, I knew that.

Then what we do with this PR done by @gagzvirk ?

What I want to know is if I left this PR open or simply closed because it do not have any explanation.

That's why my question comes up!

**Comment by lmignon** [comment]
@nhomar IMO, this one can be closed.

**Comment by yvaucher** [comment]
@gagzvirk Can you enlighten us on what is the purpose of this PR?

**Comment by JonathanNEMRY** [comment]
IMO as long as there are opened PR on 8.0-incubator we can not merge this one into 8.0

**Comment by yvaucher** [comment]
Ok then I close it for now.

**Pull request closed without merging**
