### PR TITLE
[CHG] Improve physician view

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
Improve the physician view

### CODE REVIEW

**Comment by lasley** [comment]
@JonathanNEMRY  - Hmmm I think we're conflicting here and #41. Looks like your views are better, they just need to be updated with my models?

**Comment by lmignon** [comment]
@JonathanNEMRY Can you rebase your work on #41

**Comment by JonathanNEMRY** [comment]
Hi @lasley  don't worry with this one, your PR has priority over mine has you proposed it before. I will rebase this one once yours will be merged and apply all your data model modifications into the current modifed views.

**Comment by lasley** [comment]
Woot thanks @JonathanNEMRY !

**Pull request closed without merging**
