### PR TITLE
Duration not properly handled in calendar view

### PR DESCRIPTION
**Pull request by askz**

### CODE REVIEW

**Comment by lasley** [comment]
:+1: - This will need to be merged after the 9.0 upgrade of this module - #70

**Comment by pedrobaeza** [comment]
You mustn't patch the uninstallable version. You can mention in the PR that migrate it to v9 here: https://github.com/OCA/vertical-medical/pull/69

**Comment by pedrobaeza** [comment]
@lasley, please include it in your migration PR (cherry-pick it)

**Comment by lasley** [comment]
Good call thanks @pedrobaeza - was trying to figure out the best way to include it. 

@askz  I will cherry pick your change into the 9.0 PR. Thanks for the hard work!

**Pull request closed without merging**
