### PR TITLE
[FIX][9.0] medical_medicament: Fix manifest.

### PR DESCRIPTION
**Pull request by woodbrettm**
* Set application key to False
@lasley I felt this warranted a hotfix, but if not, I can add it to the 10.0 fix list.

### CODE REVIEW

**Review by lasley — APPROVED** [review]
Simple enough, thanks @bmw95

**Comment by lasley** [comment]
@tedsalmon please review

**Review by tedsalmon — APPROVED** [review]
Simple - LGTM! 👍

**Comment by jcdrubay** [comment]
LGTM

**Pull request merged**
