### PR TITLE
[10.0][MIG][ADD] medical_base_us: v10 migration + ID type records

### PR DESCRIPTION
**Pull request by obulkin**
[MIG] ``medical_base_us``: v10 migration
* Make standard v10 migration changes
* Add ``medical_agpl`` dependency needed due to v10 restructuring and revert license back to AGPL
* Make various style improvements

[ADD] ``medical_base_us``: ID types
* Add ``res.partner.id_category`` records corresponding to various US ID types, leveraging existing validation logic where relevant. These can be used in dependent modules to add the appropriate ID fields

### CODE REVIEW

**Review by lasley — APPROVED** [review]
Thanks @obulkin

**Comment by obulkin** [comment]
I've pushed up an extra commit that modifies the unit tests in this module so that they use the correct approach for testing abstract models. The prior approach was causing errors in https://github.com/OCA/vertical-medical/pull/197.

**Review by lasley — APPROVED** [review]

**Comment by lasley** [comment]
@obulkin - please squash for merge

**Comment by obulkin** [comment]
@lasley - I've squashed down the commits not brought over from v9. This should be ready for a merge now.

**Comment by lasley** [comment]
Thanks @obulkin

**Pull request merged**
