### PR TITLE
[10.0][medical][bugfix 177] adds supplier and customer booleans as invisible fields

### LINKED ISSUE #177: [10.0] [medical] Error when access to patient
When a user accesses to a patient, he is getting an error:
`Uncaught Error: NameError: name 'supplier' is not defined`

image

### PR DESCRIPTION
**Pull request by rgarnau**
This PR fixes #177

### CODE REVIEW

**Review by lasley — APPROVED** [review]
Thanks @rgarnau

**Review by JordiBForgeFlow — APPROVED** [review]
:+1:

**Comment by JordiBForgeFlow** [comment]
@lasley Do we merge this one? I am not clear what is the merge policy for the medical repo. 3 approvers or 2 + a few days? Perhaps we should define a policy that works well for us.

**Comment by lasley** [comment]
Rebuilding Runbot - I think it's red due to the upgrade. If it passes, I'd say this is good for a quick merge due to it fixing a bug & being fairly obvious

**Comment by lasley** [comment]
Oh wait actually @rgarnau - can you please raise the version number in the manifest up by one fix version (the right most digit)?

**Comment by lasley** [comment]
Thanks @rgarnau 

Quick merged

**Pull request merged**
