### PR TITLE
[IMP] add internal/external employee flag

### PR DESCRIPTION
**Pull request by rgarnau**
This PR adds a flag in Practitioner in order to identify whether he/she is an internal or an external employee.

### CODE REVIEW

**Review by lasley — CHANGES_REQUESTED** [review]
Thanks @rgarnau 

Please raise by one feature version in the manifest. `10.0.1.00` to `10.0.1.1.0`

**Comment by rgarnau** [comment]
@lasley done!

**Review by lasley — APPROVED** [review]

**Comment by lasley** [comment]
@jbeficent - please review

**Comment by JordiBForgeFlow** [comment]
@rgarnau The problem I see is that the radio button is not visible when the user is in read mode. Only when you are in edit mode. Perhaps we should remove the `options="{'horizontal': true}`

**Comment by lasley** [comment]
Hmmmm would it make more sense to somehow indicate the internal/external with the practitioner display name for readers instead of the explicit box? Maybe if external, we could make the display name `Practioner Name (Company Name)`?

**Comment by JordiBForgeFlow** [comment]
@lasley Yes, it makes a lot of sense!

**Comment by JordiBForgeFlow** [comment]
But sometimes you will have independent practitioners, not really associated with any company.

**Comment by lasley** [comment]
Hmmmm good point. Maybe then instead of displaying the company, which probably isn't relevant anyways, just some sort of external indicator? I've seen a few companies just prefix the name with `[X] `.

**Comment by lasley** [comment]
My one problem with this strategy is that it was never immediately clear to a user what the [X] meant and it was something that either had to be trained or inferred. The people that cared about internal/external seemed to get it though.

**Comment by JordiBForgeFlow** [comment]
I can see this more of a specific customization. To some entities this attribute is not relevant enough to appear in the display name. 

The problem I see now is that it is really impossible to see if the practitioner is internal or external, by looking at the partner form.

**Comment by lasley** [comment]
Good point - ok let's just remove the horizontal then and call it a day 👍

**Comment by rgarnau** [comment]
oke, so I've removed the horizontal and the editonly and that's how it looks like:

image

Maybe it would be better to remove as well the "Employee" string and just leave the Internal/External.

**Comment by lasley** [comment]
> Maybe it would be better to remove as well the "Employee" string and just leave the Internal/External.

I agree - external is technically not an employee (at least that's the case in America). Then we get into a similar situation with the `[X]` though I think - it's not immediately clear what External or Internal would be referencing.

What if we switched the "Employee" terminology everywhere to "Entity" instead?

**Comment by rgarnau** [comment]
Oke, I like it, switched to 'Entity'!

@jbeficent could you please review?

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
