### PR TITLE
[8.0 incubator] medical medicament attributes

### PR DESCRIPTION
**Pull request by lasley**
Adds physical attribute codes to medical.medicaments. Includes Size, Color, Flavor.

These could be included in medical.medicament, but they may be needed in most contexts - hence the module.

Depends on #45

### CODE REVIEW

**Comment by lasley** [comment]
These failing tests are kind of confusing me due to the lack of test failure in the dependent branch, and the fact that I did not alter any of the files that are noted. Have our Travis checks changed or something?

**Comment by lasley** [comment]
Thank for the review @JonathanNEMRY 

Regarding the single vs multi line field declarations - I've been kind of standardizing on just putting fields on multiple lines because I've been spending a lot of time fixing them later when more attrs end up getting added. Is this frowned upon in the community?

**Comment by JonathanNEMRY** [comment]
Hi @lasley single/multi line field declaration was a detail; the main remark was the string attribute. So I give you a :+1: (code review) for this one!

**Comment by lasley** [comment]
Good call, thanks @JonathanNEMRY - I always forget those!

**Pull request closed without merging**
