### PR TITLE
[FIX] medical_base_us: Unit tests

### PR DESCRIPTION
**Pull request by obulkin**
* Fix unit tests in module by adding relevant test classes to registry, setting up their fields, and making a few other changes to the test logic

### CODE REVIEW

**Review by lasley — APPROVED** [review]
Thanks @obulkin 

@t3ddftw please review

**Review by tedsalmon — APPROVED** [review]
LGTM! 👍 

However, Is there any way that we could trigger the False return in the tests? It's the only line that isn't hit by tests :/ 
https://coveralls.io/jobs/21070934/source_files/70195254#L63

**Comment by obulkin** [comment]
@t3ddftw --- Sure thing. I just added another invalid DEA number that should cause that line to get hit.

**Review by lasley — APPROVED** [review]
Boom good job @obulkin - thank you. I'm going to quick merge this seeing as build is broken and you only edited tests

**Pull request merged**
