### PR TITLE
[8.0] [BUG] Medical Patient leap day compatibility and tests

### PR DESCRIPTION
**Pull request by lasley**
This PR Odoo-izes the medical_patient datetime handling in age computation, as well as allows for injection of a static time for testability.

Tests upgraded to match, fixing #105 & also verifying that leap day is in-fact compatible with the calculations.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check runbot error.

**Comment by lasley** [comment]
Oh crap that's my branch name - I forgot my Runbot has a module to utilize a folder hierarchy for branch versioning instead of the `8.0-`. Note the issue is that I have defined sequence.type, but that doesn't exist in 9.0.

Shall I submit under a compatible branch name? Also, would this Runbot module that I completely forgot about be something OCA wants? The folder hierarchy is much more organized IMO

**Comment by pedrobaeza** [comment]
It's curious, but the PR is against 8.0, so I don't understand the complain. I suggest to fix this PR anyways, and the other module you mention can be proposed and discussed separately.

**Comment by lasley** [comment]
Hmmm I'm not really sure how to fix it aside from just resubmitting w/ a different branch name? `ir.sequence.type` is most definitely a thing in Odoo 8. Isn't it required?

```
ParseError: "ir.sequence.type" while parsing /srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3142833-106-8c08d4/openerp/addons/medical/views/medical_sequence.xml:6, near
<record id="seq_type_medical_patient" model="ir.sequence.type">
            <field name="name">Medical Patient</field>
            <field name="code">medical.patient</field>
        </record>
```

I'll just resubmit with a compatible branch name and hope for the best. Otherwise, I'm confused 😑

**Pull request closed without merging**
