### PR TITLE
Release/8.0

### PR DESCRIPTION
**Pull request by lasley**
Hi All!

This PR incorporates all existing PRs, and fixes all merge conflicts from 8.0-incubator into 8.0. I would say that it's probably best to just work from this one and close all the others (assuming someone reviews and I actually got them all).

We have completed all the forward development that will be done on the 8.0 side of things on our end.

Unless anyone else has some changes they'd like to propose, I'd say that this is good to go directly into 8.0.

Known issues on this branch:
- `medical_prescription_sale` is only partially complete due to running into some issues with `medical_prescription_sale.wizard.crm_make_sale` that have vanished with the spiffy new 9.0 Odoo code
# Changes for this PR

This only lists changes not already accounted for in open PRs.
## Redesigned Modules
- medical_insurance - Introduced insurance plan templating (similar to medications).Redesigned most everything else
## New Modules
- medical_prescription_state - Add states to medical_prescriptions (similar to project)
- medical_pharmacy - Add pharmacy concept (similar to medical.patient)
- medical_pharmacy_us - US Locale for pharmacy
- medical_insurance_us - US Locale for insurance
- medical_medication_us - US Locale for Medication
- medical_prescription_thread - Adds message threading to Prescription Order and Lines
## New, But Broken Module

Installation is disabled, but the module work may be useful to someone so it's included. 
- medical_prescription_sale

### CODE REVIEW

**Comment by lasley** [comment]
Runbot errors & warnings have been cleared. 

Not sure what's up with that one Travis build, seems like it timed out on downloading the repo. Would someone mind rerunning it please?

**Comment by nhomar** [comment]
Travis Problems looks like Timeout issue.
I just asked a rebuild.

Let's wait, if it is confirmed we merg it.
If it is another problem I will ask @moylop260 to help you with that.

Extraordinary Good Job. ;-)

**Comment by lasley** [comment]
Thanks @nhomar !

**Comment by nhomar** [comment]
@lasley 

I will merg it as it is, in order to no delay.

But I think you should improve some things:
1. Travis is testing only "medical"
2. medical only depends of product.
3. You do not need add base as dependency odoo recursivity take this into account.

But BTW, as a first release this is way better then what we had before.

Once you enable other tests may be you will find other issues but it is normal, let's move forward.

Thanks for the effort.
PS: If nobody againts my decisition (we need 1 more +1 you have mine.)

**Comment by pedrobaeza** [comment]
There are too much commit. I would prefer to squash some commits from the same author in one, because they are very meaningless.

**Comment by nhomar** [comment]
@pedrobaeza I think this is too much work related in the parallel branch, I think is meaningless ask for thet when the work was done on another branch... but if @lasley is Ok, Just squash them, if not, I ask @pedrobaeza give a first +1 in order to move forward.

**Comment by pedrobaeza** [comment]
@nhomar, look for some of them (there are even reverts):

```
Remove duplicates in unported
Fix action ids in insurance views
Revert "Remove `_name` from inherited models" …
Remove medical_insurance import
Add template and remove company from insurance_us imports
Add missing quote
Add required and cascade deletion on join cols
Remove inherit_id from action 
```

They don't have any meaning in this merge operation. We have a very dirty commit history, so this can be help a bit. It's only a bit effort more.

**Comment by lasley** [comment]
@pedrobaeza - 

Do we have any sort of guideline on what I should be putting in my commits in terms of content? I was trying to follow the guideline of a logical changeset that didn't impact multiple modules. Unfortunately there were times that I was bounding back and forth between modules.

Also you mentioned revert- is there a strategy other than revert that accomplishes the same goal? Something with rebase that I'm missing?

**Comment by pedrobaeza** [comment]
It's not a question of guides, but join several commits that makes very little changes (1 to 10 lines), all together, in a more sense message that matters, like "[MIG] <module_name>: Adjustments to this or that" instead of that technical detail.

**Comment by lasley** [comment]
Honestly I'm not sure if my rebase skills are good enough to actually accomplish this. I just gave it a shot, but the amount of conflicts on a continuing basis makes me think I'm doing something wrong. It's >200 conflicts for a good about of steps :frowning:

**Comment by moylop260** [comment]
Please, Could you look lint checks https://travis-ci.org/OCA/vertical-medical/jobs/104177924#L382?

**Comment by nhomar** [comment]
@moylop260 can you help to @lasley to set the correct lint checking?

Why travis green if lint failing?

**Comment by moylop260** [comment]
@lasley 
The history is very large...
But a summary is:
- travis is green because we have new checks that won't affect your build status for now.
  You have the decision to fix or not fix.
  But if you fix it all our will be happy.
- RST syntax errors
- license
- duplicated xml id
- Deprecated libraries
- utf comment
  ...

If you have a problem to fix it you feel free to reply this issue with your question.

**Comment by lasley** [comment]
@moylop260 

Thanks for the breakdown. I think I actually caught the tail end of this history when I started watching the `maintainer-tools` repo.

Is there something I need to do to get these tests working on my Travis? 

Also, what is this `image` key that is being required in the `__openerp__` manifest? I'm not able to find any examples of it being used in our codebase.

All the other errors seem pretty straightforward; I am in the process of resolving now.

**Comment by lasley** [comment]
Lints other than the `images` manifest have been resolved. If someone could point me to an example of that, I'd be happy to add them as well.

A few of the deprecations I did not bother with, as we will be completely overhauling them on the 9.0 initiative:
- medical.medical_appointment - osv usage has already been corrected in 9.0 branch w/ introduction of medical_appointment & medical_base_history
- medical.medical_speciality, medical.wizard.medical_physician_unavailable, medical.product_product - osv usage has already been corrected in 9.0 branch w/ introduction of medical_physician module

Something I noticed with the linting of the `license` attr in the manifest - it has to be encapsulated in `'` instead of `"`. I personally like this, as it is the Pythonic way of declaring a string; I just wanted to make sure it was intended :smile:

**Comment by moylop260** [comment]
Hello @lasley 
Thank you for fixes
- We can live without `images` key for now.
- Use `license` instead of `licence`
  - Example here: https://github.com/laslabs/vertical-medical/blob/4565f87661341d5b1e224ab0db1ffa24e586d73d/medical_pharmacy_us/__openerp__.py#L45
- Use CamelCase in class name.
  - Example use "MedicalAppointmentHistory" instead of "MedicalAppointment_history"
  - Example use "MedicalPhysicianUnavailableWizard" instead of "medical_physician_unavailable_wizard".

**Comment by lasley** [comment]
@moylop260 - Ahh good catch with `licence`, didn't notice the mispelling there. Missed the camel casing too, whoops! Fixed up!

**Comment by pedrobaeza** [comment]
OK, I won't block anymore this PR due to the commits, for the good-shake of having it merged for continuing with the migration.

Congratulations for the hard work.

**Comment by lasley** [comment]
Thank @pedrobaeza - will take all these suggestions into my work, as well as the new trainees. We've also revamped the OCA contribution docs, which we will submit once finalized/converted to MD

**Comment by JonathanNEMRY** [comment]
Great!
Thank you for your work @lasley ! We can now continue with a cleaner 8.0!

**Pull request merged**
