### PR TITLE
[FIX][9.0] medical_patient_dob: Support no date format

### PR DESCRIPTION
**Pull request by lasley**
* Add support for no or false date format

### CODE REVIEW

**Comment by lasley** [comment]
@t3ddftw please review

**Review by tedsalmon — COMMENTED** [review]
One minor detail which relates to my review on https://github.com/laslabs/vertical-medical/pull/43; so depending on where you answer me first, I'll approve :)

**Review by tedsalmon — APPROVED** [review]
Approving per response on https://github.com/laslabs/vertical-medical/pull/43.

**Review by susport — COMMENTED** [review]
is 👍 But in this module should validate the date of birth.

**Comment by lasley** [comment]
> But in this module should validate the date of birth.

@susport - As in validate that it is set on the patient?

**Comment by susport** [comment]
@lasley Only validate that an invalid date does not enter, greater than the current date

**Comment by lasley** [comment]
@susport - I like this feature idea, although I think maybe we should push it back a bit into the [core medical.patient model, where the dob is defined](https://github.com/OCA/vertical-medical/blob/9.0/medical/models/medical_patient.py#L28). What do you think?

FYI this module really only alters the display name of the patient in order to add the birth date everywhere. It seems this has been a common display requirement for most medical industries, and is used to quickly identify the correct patient in the event of having the same name.

**Pull request merged**
