### PR TITLE
[9.0][FIX] Product UoM Data

### PR DESCRIPTION
**Pull request by woodbrettm**

### CODE REVIEW

**Comment by woodbrettm** [comment]
@lasley

**Review by lasley — APPROVED** [review]
Thanks @bmw95. Please also make this change in `product-attribute/product_uom`

@tedsalmon please review

**Comment by woodbrettm** [comment]
@lasley do you want that submitted both to 9.0 and 10.0 in product-attribute?

**Review by tedsalmon — APPROVED** [review]
👍  LGTM! :)

**Comment by lasley** [comment]
@bmw95 - yes, please submit to both relevant.

Also please increment this module by a patch version in manifest

**Comment by lasley** [comment]
@bmw95 please increment this module by a patch version in manifest

**Comment by woodbrettm** [comment]
@lasley done.

**Pull request merged**
